spring:
  datasource:
    url: jdbc:mysql://elliedb.cig2pf2l0lno.ap-northeast-2.rds.amazonaws.com:3306/umc_study
    username: root
    password: rootdb2457
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000